#ifndef _kvi_sysconfig_h_
#define _kvi_sysconfig_h_
//=============================================================================
//
// System dependent configuration for KVIrc
// This file is automatically generated: do not edit
//
//=============================================================================

#define SYSTEM_SIZE_OF_SHORT_INT 2
#define SYSTEM_SIZE_OF_INT 4
#define SYSTEM_SIZE_OF_LONG_INT 8
#define SYSTEM_SIZE_OF_LONG_LONG_INT 8

#define SYSTEM_HAS_SYS_TYPES_H 1
#define SYSTEM_HAS_STRINGS_H 1
#define HAVE_SETENV 1
#define HAVE_PUTENV 1

#define COMPILE_THREADS_USE_POSIX 1
/* #undef COMPILE_THREADS_USE_WIN32 */
/* #undef COMPILE_THREADS_USE_SOLARIS_LIBTHREAD */
/* #undef COMPILE_IGNORE_SIGALARM */

/* #undef COMPILE_MEMORY_PROFILE */
/* #undef COMPILE_MEMORY_CHECKS */

#define COMPILE_CRYPT_SUPPORT 1
/* #undef COMPILE_SSL_SUPPORT */
#define COMPILE_X11_SUPPORT 1
/* #undef COMPILE_QX11INFO_SUPPORT */
/* #undef COMPILE_XSS_SUPPORT */
#define COMPILE_IPV6_SUPPORT 1
#define COMPILE_PSEUDO_TRANSPARENCY 1
/* #undef COMPILE_ENCHANT_SUPPORT */
// Do we use KDE at all?
/* #undef COMPILE_KDE_SUPPORT */
// Using KDE4 ? Implies COMPILE_KDE_SUPPORT
/* #undef COMPILE_KDE4_SUPPORT */
// Using KDE5 ? Implies COMPILE_KDE_SUPPORT
/* #undef COMPILE_KDE5_SUPPORT */
/* #undef COMPILE_WEBKIT_SUPPORT */
#define COMPILE_DBUS_SUPPORT 1
#define COMPILE_ZLIB_SUPPORT 1
/* #undef COMPILE_ENABLE_GTKSTYLE */

/* #undef COMPILE_PHONON_SUPPORT */
/* #undef COMPILE_ESD_SUPPORT */
#define COMPILE_OSS_SUPPORT 1
#define HAVE_LINUX_SOUNDCARD_H 1
#define HAVE_SYS_SOUNDCARD_H 1
/* #undef HAVE_MACHINE_SOUNDCARD_H */
/* #undef COMPILE_DCC_CANVAS */
/* #undef COMPILE_AUDIOFILE_SUPPORT */
/* #undef COMPILE_DISABLE_DCC_VOICE */
#define HAVE_LINUX_SOUNDCARD_H 1
#define HAVE_SYS_SOUNDCARD_H 1
/* #undef HAVE_SOUNDCARD_H */

#define COMPILE_DISABLE_DCC_VIDEO 1
#define COMPILE_DISABLE_OGG_THEORA 1

/* #undef COMPILE_DEBUG_MODE */

#define COMPILE_PERL_SUPPORT 1
#define COMPILE_PYTHON_SUPPORT 1

#define COMPILE_USE_DYNAMIC_LABELS 1
#define COMPILE_GET_INTERFACE_ADDRESS 1
#define HAVE_INET_ATON 1
#define HAVE_INET_NTOA 1

#define COMPILE_USE_STANDALONE_MOC_SOURCES 1

#define KVIRC_VERSION_RELEASE "5.0.0"
#define KVIRC_VERSION_BRANCH "5.0"
#define KVIRC_VERSION_CODENAME "Aria"

// KVIrc detects the modules directory on macs/win32 by itself
// this seems to be used on linux only
#if !(defined(Q_OS_MACX) || defined(MINGW) || defined(MSVC))
#define KVIRC_RESOURCES_DIR "/home/gmagoon/Downloads/KVIrc/src/kvirc/share/kvirc/5.0/"
#define KVIRC_MODULES_DIR "/home/gmagoon/Downloads/KVIrc/src/kvirc/lib/home/gmagoon/Downloads/KVIrc/src/kvirc/kvirc/5.0/modules"
#endif

#endif //!_kvi_sysconfig_h_
