#ifndef _kvi_sysbuildinfo_h_
#define _kvi_sysbuildinfo_h_
//=============================================================================
//
// System dependent configuration for KVIrc
// This file is automatically generated: do not edit
//
//=============================================================================

#define KVIRC_BUILD_DATE "2019-08-30 04:46:30 UTC"
#define KVIRC_BUILD_COMMAND "/usr/bin/cmake"
#define KVIRC_BUILD_FLAGS "MANDIR=share/man;CMAKE_INSTALL_PREFIX=/home/gmagoon/Downloads/KVIrc/src/kvirc;LIB_SUFFIX=/home/gmagoon/Downloads/KVIrc/src/kvirc;Threads=POSIX"
#define KVIRC_BUILD_SYSTEM_NAME "Linux"
#define KVIRC_BUILD_CPU "x86_64"
#define KVIRC_BUILD_COMPILER "/usr/bin/c++"
#define KVIRC_BUILD_COMPILER_FLAGS ""
#define KVIRC_BUILD_REVISION "5.0.0-53-g2fe1a3bca-dirty"
#define KVIRC_SOURCES_GOT_DATE_FROM_GIT

#ifdef KVIRC_SOURCES_GOT_DATE_FROM_GIT
	#define KVIRC_SOURCES_DATE_GIT "20190628"
	#define KVIRC_SOURCES_DATE_GIT_HEX 0x20190628
#endif

#endif //!_kvi_sysbuildinfo_h_
