# Install script for directory: /home/gmagoon/Downloads/KVIrc/src/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/gmagoon/Downloads/KVIrc/src/kvirc")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/gmagoon/Downloads/KVIrc/src/modules/about/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/action/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/actioneditor/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/addon/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/aliaseditor/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/avatar/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/chan/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/channelsjoin/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/classeditor/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/codetester/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/config/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/context/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/dcc/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/dialog/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/editor/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/eventeditor/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/file/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/filetransferwindow/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/fish/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/help/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/http/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/ident/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/iograph/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/lamerizer/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/language/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/links/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/list/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/log/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/logview/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/mask/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/math/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/mediaplayer/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/mircimport/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/my/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/notifier/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/objects/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/options/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/package/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/perlcore/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/popup/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/popupeditor/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/proxydb/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/pythoncore/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/raweditor/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/regchan/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/reguser/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/rijndael/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/rot13/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/serverdb/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/setup/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/sharedfile/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/sharedfileswindow/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/snd/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/socketspy/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/spaste/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/str/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/system/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/texticons/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/term/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/theme/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/tip/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/tmphighlight/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/toolbar/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/toolbareditor/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/torrent/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/trayicon/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/upnp/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/url/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/userlist/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/window/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/perl/cmake_install.cmake")
  include("/home/gmagoon/Downloads/KVIrc/src/modules/python/cmake_install.cmake")

endif()

